### ISSUE TITLE
Unity socket cannot deal with odd non-standard characters

### ISSUE THREAD

**Issue by nohumanman** [nohumanman/descenders-modkit#173]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/var/www/descenders-modkit/unity_socket_server.py", line 102, in create_client
    message = message_buffer + data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 5: invalid continuation byte
```

**Comment by nohumanman** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/var/www/descenders-modkit/unity_socket_server.py", line 102, in create_client
    message = message_buffer + data.decode()
```
